### PR TITLE
vim/less compatibility

### PR DESCRIPTION
**Pull request by shiar**
Adds some (alternate) key bindings, minimal search option, and mutt colour scheme.

### CODE REVIEW

**Comment by okbob** [comment]
the keys '0..4' are used for fixed columns specification. In this moment I am rewriting pspg to don't use ncurses pads due high memory requests.

**Comment by shiar** [comment]
> the keys '0..4' are used for fixed columns specification.

I don't think I'm touching those keys, am I?

> In this moment I am rewriting pspg to don't use ncurses pads due high memory requests.

Does this conflict? I can retry later if you want.

**Comment by okbob** [comment]
I am not sure what will be changed - minimally access to raw data will be different.

**Comment by okbob** [comment]
merged, thank you

**Pull request merged**
