### PR TITLE
setup Travis CI

### PR DESCRIPTION
**Pull request by simi**
Hello. I have prepared testing environment on Travis CI. To enable it in this repository check https://travis-ci.com/getting_started and follow first step (login via GitHub and enable repository). You can ping me back once done, I can force push in here to trigger CI build for this pull request.

example output at my fork - https://travis-ci.org/simi/pspg/builds/511640582

It uses Ubuntu 14.04.05 LTS. If you're interested in another system (or even another CI) feel free to ping me I can do my best to change this pull request to fit project needs. I can try to setup MacOS build on Travis CI as well. 

I'm not sure about Windows support, but there are free Windows CIs today available as well if needed.

### CODE REVIEW

**Comment by okbob** [comment]
Thank you

**Comment by simi** [comment]
:thinking: I see it is still not enabled at https://travis-ci.org/okbob/pspg. Is there anything I can help with?

**Comment by okbob** [comment]
It should be done now

út 26. 3. 2019 v 21:42 odesílatel Josef Šimánek <notifications@github.com>
napsal:

**Comment by simi** [comment]
looks good :+1:

**Pull request merged**
