### PR TITLE
Define _GNU_SOURCE and include sys/types.h for uint

### PR DESCRIPTION
**Pull request by maxice8**

### CODE REVIEW

**Comment by okbob** [comment]
please, can me provide more information for this pull request?

**Comment by maxice8** [comment]
uint is only available for musl libc users when _GNU_SOURCE is defined and sys/types.h is included.

**Comment by okbob** [comment]
I looked there, and I prefer more simple (and I don't afraid about portability) solution - see 21224c0b39ae80c3ce756dd213bbeb656ec26ee0. Is it ok for musl libc?

**Comment by maxice8** [comment]
Sure, seems better

**Comment by okbob** [comment]
ok. Thank you for report of this issue :)

**Pull request closed without merging**
